### ISSUE TITLE
Any solution to Fn:Join layers?

### ISSUE THREAD

**Issue by bart** [mooyoul/serverless-latest-layer-version#8]
It looks like this plugin only works for layer strings but won't work when concatenating strings like this:

```
layers:
      - Fn::Join:
        - ""
        - ["arn:aws:lambda:", {Ref: "AWS::Region"}, ":", {Ref: "AWS::AccountId"}, ":layer:shared:latest"]
```

Any solution to this? Thanks a lot!

**Comment by mooyoul** [comment]
Yes, I know that limitation. Since resolving/replacing layer version is performed before CloudFormation deployment, I have to parse entire CloudFormation template. It's super hard to implement all CloudFormation function support like `Fn::Join`, `Fn::Sub`. So i decided to support string value only.

Luckily, It seems that your example only requires pseudo parameter references. 
In this case, Use this plugin with [serverless-pseudo-parameters plugin](https://github.com/svdgraaf/serverless-pseudo-parameters). It has been successfully tested and it will work.

Hope this helps! :)

**Comment by bart** [comment]
I will check it out, cool! Thank you very much

**Comment by nbusser** [comment]
Hey, sorry for bumping this very old issue, but I was thinking of something.
Can't we just mimic the behaviour of Fn::Join, then spot the `latest` keywork and replace it with fetched layer version?
I'm thinking of a really simple recursive function like:
```javascript
processJoin(node) {
  if (node['Fn::Join'] === undefined) {
    return node;
  }

  const join = node['Fn::Join'];
  const delimiter = join[0];
  
  let joined = '';
  for (const value of join[1]) {
    joined = joined + this.processJoin(value) + delimiter;
  }
  return joined.slice(0, -1);
}  
```
